### ISSUE TITLE
Question about Json formatting

### ISSUE THREAD

**Issue by bolanosdev** [ethancarlsson/nvim-hurl.nvim#1]
hi Ethan thanks for creating this plugin.

I think I was able to figure out how to run a couple of hurl commands with your plugin.
![Screenshot 2024-01-31 at 2 54 40 PM](https://github.com/ethancarlsson/nvim-hurl.nvim/assets/2865089/4e7b651e-da2c-4259-a402-bc50003db125)

I was just wondering if you could share how are you indenting the json output
your [blog](https://www.ethancarlsson.dev/blog/exploringapiswithneovimandhurl) post doesn't identify that would be very useful

Thanks!

**Comment by ethancarlsson** [comment]
Hey,

I'm glad it's been useful.

This plugin doesn't do any kind of formatting for JSON or any other file types, so I use a different tool for that.

I used to use [JQ](https://jqlang.github.io/jq/) using this command in vim `%!jq '.'`, it's great but it throws an error on invalid JSON (which I'm getting a lot of lately). I'm using json-lsp which I just installed with via [mason](https://github.com/williamboman/mason.nvim/tree/main), it's a bit slow though, so I'm looking for another alternative.
